---
env:
  matrix:
    v=5.4
    v=5.5
    v=5.6
    v=7.0
    v=7.1
    v=7.2

stages:
  - base
  - mods
  - prod
  - work

before_script:
  # Regenerate Dockerfiles and make sure nothing has changed (every stage)
  - make generate
  - git diff-index --quiet HEAD || { echo "Build Changes"; git diff; git status; false; }

jobs:
  include:
    - stage: base
      script:
        - echo "${v}-base"
    - stage: mods
      script:
        - echo "${v}-mods"
    - stage: prod
      script:
        - echo "${v}-prod"
    - stage: work
      script:
        - echo "${v}-work"
