---

# Available Jinja2 variables:
# ---------------------------
# * {{ php_all_versions }}:  Array of all PHP versions


all:
  type: pecl
  run_dep: [uuid]
  build_dep: [uuid-dev]

5.6:
  type: pecl
  version: 1.0.5

5.5:
  type: pecl
  version: 1.0.5

5.4:
  type: pecl
  version: 1.0.5

5.3:
  type: pecl
  version: 1.0.5
