---

# Available Jinja2 variables:
# ---------------------------
# * {{ php_all_versions }}:  Array of all PHP versions


all:
  type: git
  git_url: https://github.com/phpredis/phpredis
  git_ref: $(git for-each-ref --format='%(refname)' refs/tags | grep -E 'tags/[.0-9]+$' | sed 's|.*tags/||g' | sort -V | tail -1)
  command: |
    REDIS_ARGS=""; \
    if [ -d "/usr/local/include/php/ext/igbinary" ]; then \
      REDIS_ARGS="${REDIS_ARGS} --enable-redis-igbinary"; \
    fi; \
    if [ -d "/usr/local/include/php/ext/msgpack" ]; then \
      REDIS_ARGS="${REDIS_ARGS} --enable-redis-msgpack"; \
    fi; \
    phpize \
    && ./configure --enable-redis ${REDIS_ARGS} \
    && make -j$(getconf _NPROCESSORS_ONLN) \
    && make install \

8.2:
  type: git
  git_url: https://github.com/phpredis/phpredis
  git_ref: $(git for-each-ref --format='%(refname)' refs/tags | grep -E 'tags/[.0-9]+$' | sed 's|.*tags/||g' | sort -V | tail -1)
  command: |
    REDIS_ARGS=""; \
    if [ -d "/usr/local/include/php/ext/igbinary" ]; then \
      REDIS_ARGS="${REDIS_ARGS} --enable-redis-igbinary"; \
    fi; \
    if [ -d "/usr/local/include/php/ext/msgpack" ]; then \
      REDIS_ARGS="${REDIS_ARGS} --enable-redis-msgpack"; \
    fi; \
    phpize \
    && ./configure --enable-redis ${REDIS_ARGS} \
    && sed -i'' 's/ops->hash_init(ctx);/ops->hash_init(ctx, NULL);/g' library.c \
    && sed -i'' 's/ops->hash_init(ctx);/ops->hash_init(ctx, NULL);/g' redis_array_impl.c \
    && make -j$(getconf _NPROCESSORS_ONLN) \
    && make install \

8.1:
  type: git
  git_url: https://github.com/phpredis/phpredis
  git_ref: $(git for-each-ref --format='%(refname)' refs/tags | grep -E 'tags/[.0-9]+$' | sed 's|.*tags/||g' | sort -V | tail -1)
  command: |
    REDIS_ARGS=""; \
    if [ -d "/usr/local/include/php/ext/igbinary" ]; then \
      REDIS_ARGS="${REDIS_ARGS} --enable-redis-igbinary"; \
    fi; \
    if [ -d "/usr/local/include/php/ext/msgpack" ]; then \
      REDIS_ARGS="${REDIS_ARGS} --enable-redis-msgpack"; \
    fi; \
    phpize \
    && ./configure --enable-redis ${REDIS_ARGS} \
    && sed -i'' 's/ops->hash_init(ctx);/ops->hash_init(ctx, NULL);/g' library.c \
    && sed -i'' 's/ops->hash_init(ctx);/ops->hash_init(ctx, NULL);/g' redis_array_impl.c \
    && make -j$(getconf _NPROCESSORS_ONLN) \
    && make install \

5.6:
  type: pecl
  version: 4.3.0

5.5:
  type: pecl
  version: 4.3.0

5.4:
  type: pecl
  version: 4.3.0

5.3:
  type: pecl
  version: 4.3.0

5.2:
  type: pecl
  version: 2.2.7
