---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: lint


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  # Runs on Pull Requests
  workflow_dispatch:
  pull_request:


# -------------------------------------------------------------------------------------------------
# What to run
# -------------------------------------------------------------------------------------------------
jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      # ------------------------------------------------------------
      # Setup repository
      # ------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # ------------------------------------------------------------
      # Lint repository
      # ------------------------------------------------------------
      - name: Lint Files
        run: |
          make lint-files

      - name: Lint Yaml
        run: |
          make lint-yaml

      - name: Lint Changelog
        run: |
          make lint-changelog

      - name: Diff generated Docker files
        run: |
          make gen-dockerfiles
          git diff --quiet || { echo "Build Changes"; git diff; git status; false; }
