---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: lint


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  # Runs on Pull Requests
  pull_request:


# -------------------------------------------------------------------------------------------------
# What to run
# -------------------------------------------------------------------------------------------------
jobs:
  lint:
    name: "[ ${{ matrix.job }} ]"
    runs-on: ubuntu-latest
    steps:
      # ------------------------------------------------------------
      # Setup repository
      # ------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v2

      # ------------------------------------------------------------
      # Lint repository
      # ------------------------------------------------------------
      - name: Lint workflow
        id: vars
        run: |
          make lint-workflow

      - name: Diff generated Docker files
        run: |
          make gen-readme
          git diff --quiet || { echo "Build Changes"; git diff; git status; false; }
